# Generated by Django 2.1.4 on 2018-12-10 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renderHTML', '0004_auto_20181207_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('econtacts', models.CharField(max_length=15)),
                ('eimage', models.ImageField(upload_to='Employee')),
            ],
            options={
                'db_table': 'emp',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='renderHTML.Dish'),
        ),
    ]
